name: Clean logs
run-name: Clean runs logs older than one day

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 1' # every Monday

jobs:
 Cleaning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: igorjs/gh-actions-clean-workflow@main
        with:
          runs_older_than: 1 
          token: ${{ github.token }}
          runs_to_keep: 1
      - uses: gautamkrishnar/keepalive-workflow@v2