name: DevSecOps

on:
  workflow_dispatch:

jobs:
  secrets:
    runs-on: ubuntu-latest
    env:
      SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN }}
    steps:
      - uses: actions/checkout@v4

      - name: scan secrets with Spectral
        uses: spectralops/spectral-github-action@v5
        with:
          spectral-dsn: ${{ env.SPECTRAL_DSN }}
          spectral-args: scan --ok --engines secrets --include-tags base,audit

  IaC:
    runs-on: ubuntu-latest
    env:
      SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN }}
    steps:
      - uses: actions/checkout@v4

      - name: scan IaC with Spectral
        uses: spectralops/spectral-github-action@v5
        with:
          spectral-dsn: ${{ env.SPECTRAL_DSN }}
          spectral-args: scan --ok --engines iac --include-tags base,azure
  SAST:
    runs-on: ubuntu-latest
    env:
      SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN }}
    steps:
      - uses: actions/checkout@v4
      - uses: bearer/bearer-action@v2
        with:
          path: "./devsecops/src/frontend"
          skip-rule: javascript_lang_dynamic_regex,javascript_lang_logger_leak

  SCA:
    runs-on: ubuntu-latest
    env:
      SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Restore dependencies
        run: dotnet restore ./devsecops/src/frontend/CafeReadConf.sln

      - name: dotnet publish
        run: dotnet publish -c Release -o ./myapp --property WarningLevel=0
        working-directory: ./devsecops/src/frontend

      - name: scan SCA with Spectral
        uses: spectralops/spectral-github-action@v5
        with:
          spectral-dsn: ${{ env.SPECTRAL_DSN }}
          spectral-args: scan --ok --engines oss --include-tags base,audit

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/dotnet@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif --file=./devsecops/src/frontend/CafeReadConf.sln --severity-threshold=medium

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif

  Docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: hadolint
        run: |
          echo 'Downloading Hadolint to lint Dockerfile...'
          wget https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
          chmod +x hadolint-Linux-x86_64
          mv hadolint-Linux-x86_64 hadolint

          echo 'Start Dockerfile lint...'
          ./hadolint Dockerfile -f tty > results.txt

          echo 'Results:'
          cat results.txt
        working-directory: ./devsecops/src/frontend

  build:
    needs: [secrets, SCA, Docker, IaC, SAST]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore ./devsecops/src/frontend/CafeReadConf.sln

      - name: Build
        run: dotnet build --no-restore --configuration Release --property WarningLevel=0
        working-directory: ./devsecops/src/frontend

      - name: dotnet publish
        run: dotnet publish -c Release --property WarningLevel=0
        working-directory: ./devsecops/src/frontend

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./devsecops/src/frontend/bin/Release/net8.0/publish

  deployToDev:
    needs: [build]
    runs-on: windows-latest
    environment:
      name: "dev"
      url: ${{ steps.deploy-to-webapp-dev.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp-dev
        uses: azure/webapps-deploy@v2
        with:
          app-name: "ghactions-dev"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DEV }}
          package: .

  DAST:
    needs: [deployToDev]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: "ghcr.io/zaproxy/zaproxy:stable"
          target: "https://ghactions-dev-gjbyf4c5hhhzgecw.westeurope-01.azurewebsites.net"
          rules_file_name: "devsecops/.zap/rules.tsv"
          cmd_options: "-a"

  LoadTest:
    needs: [deployToDev]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Login to Azure
        uses: azure/login@v1
        continue-on-error: false
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Azure Load Testing"
        uses: azure/load-testing@v1
        with:
          resourceGroup: "rg-book-gha"
          loadTestConfigFile: "devsecops/.load/loadtest.yaml"
          loadTestResource: "loadtestbookgha"

  deployToProd:
    needs: [LoadTest, DAST]
    runs-on: ubuntu-latest
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "ghactions-prd"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PRD}}
          package: .
