name: Generate powerpoint

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  GenerateFile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
           
      - run: sudo apt-get update
        name: Apt-get update

      - name: install pandoc
        run: sudo apt-get install --assume-yes pandoc 
        
      - name: Build PPTX version
        run: pandoc content.md --output=demo.pptx
        working-directory: ./powerpoint
      
      - name: Build HTML version
        run: pandoc --to=revealjs --standalone content.md --output=demo.html -V revealjs-url="https://cdn.jsdelivr.net/npm/reveal.js@3.9.2"
        working-directory: ./powerpoint

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Generated documents
          retention-days: 1
          path: |
            ./powerpoint/*